apiVersion: v1
kind: Service
metadata:
  labels:
    name: backend
  name: backend
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
  selector:
    app: backend

---

apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
data:
  mongodb-uri: very-secret-token-very-secret-token-very-secret-token-very-secret-token-very-secret=====

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: phico/backend/backend:1.0
        imagePullPolicy: Always
        name: backend
        ports:
        - name: backend
          containerPort: 3000
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: mongodb-uri
